### ISSUE TITLE
Celluloid::IO integration?

### ISSUE THREAD

**Issue by tarcieri** [guard/listen#159]
I think it'd be interesting if `listen` could leverage Celluloid::IO. This should be fairly straightforward for any of the adapters that can expose an IO object, although Celluloid::IO doesn't presently have APIs to "asyncify" existing IO objects.

This would eliminate the need to kick off filesystem monitoring in a separate thread, and allow actors themselves to listen for events directly while still being able to process incoming methods/messages.

I'm opening this ticket in hopes we can discuss what Celluloid::IO would need to expose to make this happen.

Also, would there be interest in leveraging filesystem monitoring via nio4r? It could use libev's filesystem monitoring support and provide a cross-platform abstraction for utilizing NIO2's filesystem monitoring support on Java platforms

**Comment by antitoxic** [comment]
Having this https://github.com/guard/listen/issues/246  isn't this for closing?

**Comment by e2** [comment]
@antitoxic - it's actually unrelated, because #246 is related to just the TCP server (I've updated the title - thanks), while this is about avoiding extra threads in Listen.

**Comment by tarcieri** [comment]
FWIW, I would like to add some nio4r features to Google Summer of Code. Filesystem monitoring could definitely be one

**Comment by e2** [comment]
@tarcieri - as for Linux, the Zeus project compiles a inotify wrapper to pipe messages through stdout to the main process, so at least this adapter could use Celluloid:IO right now (without much work). 

But actually doing so just on Linux isn't practical though - since Listen is basically one huge workaround for a lack of decent file system monitoring on Windows and OSX.

In fact, the biggest pain in the ass is OSX, because I have to use a separate thread for each watched directory - just to be able to map an event to a given watched directory (rb-fsevent workaround).

**Comment by e2** [comment]
I'm closing this since Listen 3.x no longer depends on Celluloid (because Listen is practically not a good use case for Celluloid) nor Celluloid:IO (TCP support will be in a separate gem).
