### ISSUE TITLE
3.0 regressions

### ISSUE THREAD

**Issue by rubys** [guard/listen#325]
The following worked on 2.10, but fails on 3.0.  Note that uncommenting out the require statements will get you further on 3.0, but not to completion:

```
require 'listen'
# require 'pathname'
# require 'timeout'

p File.expand_path('..', __FILE__)
listener = Listen.to(File.expand_path('..', __FILE__)) do |mod, add, del|
 p [mod, add, del] 
end
listener.start
listener.pause
listener.start
```

**Comment by rubys** [comment]
I'm also getting warnings:

```
/Library/Ruby/Gems/2.0.0/gems/listen-3.0.0/lib/listen/event/queue.rb:15: warning: toplevel constant Queue referenced by Thread::Queue
/Library/Ruby/Gems/2.0.0/gems/listen-3.0.0/lib/listen/event/loop.rb:15: warning: toplevel constant Queue referenced by Thread::Queue
```

The fix for this would be to drop `Thread::` on those two lines.

**Comment by e2** [comment]
Thanks for reporting this! You're awesome!

I didn't test Listen in isolation properly - I'll get these fixed as soon as I can. (I never found a good way of testing Listen in isolation - usually other gems pull in the requirements so everything "works" during tests).

As a tip, you can set the `LISTEN_GEM_DEBUGGING=2` environment variable to see debugging info.

Once I fix the few issues brought up here, you'll also need a `sleep` at the end, since `Listen` is non-blocking (I'm planning on adding a blocking mode, since it's quite useful and saves a thread - see here:)

As a side note, the semantics of pause are supposed to be:
- pause = suspend responding to events (calling the callback, but allow for accumulating and optimizing changes)
- stop = stop listening to changes (which means changes can be missed, the internal snapshot record can become inconsistent, etc, and so stop() is generally avoided. If you have performance issues - e.g. high CPU usage and you think stop helps, open a ticket, and I'll see what can be done).
