### ISSUE TITLE
'debug' option is obsolete?

### ISSUE THREAD

**Issue by david-ding** [guard/listen#346]
Setting debug: true doesn't seem to do anything, despite the documentation says it should have the same effect as setting the environment variable LISTEN_GEM_DEBUGGING=1.

**Comment by e2** [comment]
Quite likely, since 3.x:

TODO here:

https://github.com/guard/listen/blob/master/lib/listen/listener/config.rb#L6

And since the debug log level is not globally set:

https://github.com/guard/listen/blob/457c3cb47c706855c61c2d204a3657b6af157df1/lib/listen/logger.rb#L12

I don't think the option makes sense any more.

**Comment by e2** [comment]
I've fixed the README.

**Comment by david-ding** [comment]
Thanks!
