### ISSUE TITLE
Uninstallable on JRuby 1.7

### ISSUE THREAD

**Issue by perlun** [guard/listen#389]
Hi,

Because of the recent change to use `ruby_dep`, we have now started making the `listen` gem uninstallable on JRuby 1.7 versions. This has worked fine previously. The error we are getting is the following:

```
Installing ruby_dep 1.2.0

Gem::InstallError: ruby_dep requires Ruby version >= 2.2.3, ~> 2.2.
```

I think we need to patch `ruby_dep` to support it I guess; will probably add an issue to that repo as well later tonight.

(JRuby 1.7 is still actively maintained upstream. Does the listen gem really _require_ Ruby version 2.2 or was the change made because it's simpler to support fewer ruby versions?)

If we don't want to fix this (which I think could be understandable), I think we should then perhaps add to the `README.md` file a note saying which Ruby versions are supported. Older versions of `listen` still are likely to support the JRuby 1.7 series.

**Comment by e2** [comment]
The Readme for ruby_dep should explain things better. Please open an issue
there if you have questions. Basically, Travis builds are the authoritative
source of what's supported. The best action is upgrading Ruby and/or
putting pressure on hosting providers to offer/support at least MRI 2.2.4
and JRuby 9.0.5.0.

**Comment by e2** [comment]
As for the answer: "does the Listen gem really require Ruby version 2.2?" the real answer is: I don't know, and it's "too expensive" to make the promise that it will be.

Listen makes extensive uses of threads, queues and filesystem API - so supporting any Ruby is hard to guarantee and time consuming. Currently some tests are failing on JRuby 9.0.5.0 even. I believe it's just timing issues in tests, but I can't be sure. Previously uncovered a serious functionality bug in JRuby due to differences in JRuby vs MRI API - so I can't even assume JRuby 9.0.4.0 (2.2.2) works.

With JRuby, at some point, the difference between "bug" and "API" gets really obscure. Same with Rubinius (which isn't supported).

I need to focus on an architecture overhaul, so I want to support the bare minimum of Rubies. This mean either people upgrade to the latest, or they lock to the patch levels they approve.

For a longer discussion, see here: https://github.com/guard/listen/issues/390#issuecomment-217124756

**Comment by e2** [comment]
The best solution:

1. Upgrade Ruby
2. Lock Listen to match the "locked" Ruby version and ask for backporting patches if needed. (But please always give exact Ruby version, desired Listen major and minor, and a compelling use case).

If it's about Travis builds, just disable them or ignore failures. Patching Listen to fix "broken Travis builds" for outdated Rubies doesn't make sense on a practical user-oriented level.

If you do care about Travis builds, you MUST lock versions of ALL your gems to PATCHLEVEL versions for predictable builds. (Otherwise you're just testing a random set of gems every time).

**Comment by e2** [comment]
FWIW, I started a wiki page about this: https://github.com/guard/listen/wiki/Support-for-older-versions-of-Ruby.

And just like it says there, if you absolutely can't upgrade to the same JRuby tested on Travis here, open a backporting request as described in that Wiki. (I might be breaking a lot of things unintentionally with the overhaul, so even if the API stays 3.x, I can't promise things will work on "every" Ruby version anyway).

Until I get a strong compelling use case where JRuby cannot be upgraded to 0.9.0.5 and the issue cannot be solved with backporting requests (which I prefer), this is pretty much "won't fix", because Bundler should be improved to automatically select earlier versions if Listen if possible.

Let me know if you need anything else. (If you need something more specific for your situation which isn't covered, open a new issue).

**Comment by perlun** [comment]
Thanks for the answers! Will continue in another thread.
