### ISSUE TITLE
Ruby 2.1 support

### ISSUE THREAD

**Issue by gpakosz** [guard/listen#397]
Hello,

Would you consider bringing back support for Ruby 2.1?

Debian stable (jessie) has 2.1.5 (+ security fixes) and jessie-backports won't ever have Ruby 2.3 which is currently in Debian testing (stretch): see https://lists.debian.org/debian-backports/2016/05/msg00109.html

Guard is effectively unusable on Debian stable since commit 2e5c4099e7d1962e596861b0ab24fffd519b3b11.

Thanks in advance.

**Comment by e2** [comment]
Thanks for asking.

This is probably the *most* reasonable request for backwards support I've heard in a long time. Debian is probably the *only* reason out there to consider supporting Ruby < 2.2.

Before I address the issue, a few points regarding the linked email:

> That is not true. Ruby 2.1 is *not* EOL, it still gets security support.

"Security support" != "support"

As mentioned here:

https://www.ruby-lang.org/en/news/2016/03/30/ruby-2-1-9-released/

"After this release we will never backport any bug fixes to 2.1 except security fixes. "

If a version is not getting bug fixes, it effectively means: not getting support.

"not fixing bugs" = "no support"

Now, the fact that Debian maintainers work extremely hard to backport bugfixes effectively means it's a "Debian version of Ruby 2.1", and not an "official version of Ruby 2.1".

So what you're asking for here is: adding support for a supported Debian version of Ruby 2.1.

> whenever we add a new version of ruby we need to rebuild all packages with native extensions, and that is clearly not something we can responsibly do in the backports repository.

This makes a lot of sense - there's too much work in rebuilding a large list of packages just to add support for a newer version of Ruby.

The key issue here however is: Debian has infrequent release cycles. Of course, it's hard work to support more frequent release schedules. Still, there's a huge gap between Ruby 2.1 and Ruby 2.3 in terms of a timeline.

I actually have the same issue: I simply cannot afford to spend time dealing with, supporting and maintaining Ruby version <= 2.1, especially if Rails will be exclusively Ruby >= 2.2.

So ironically, my reason for not supporting Ruby <= 2.1 is pretty much the same as Debian maintainers reasons for supporting Ruby 2.1: too much work, no payoff.

My overall recommendation is either:

* upgrade from Debian stable to something newer (it's not like "stable" will guarantee a lack of issues with gems anyway, and production servers would have to be tested either way if gems are upgraded)

or

* lock to Listen 3.0.x - and then track issues and ask for backports (I will backport important bugfixes if they're important and if I remember, but don't count on it being the rule)

or even lock to Listen 2.x (unless it's for Rails development - Listen 3.x is better for `spring`)

> Guard is effectively unusable on Debian stable since commit 2e5c409.

Not true at all!

You can lock to `~> 3.0.x` (to get backported bugfixes from 3.x) or `~> 2.x` (if you still need TCP support which was dropped in 3.x - although you'd have to ask for backports explicitly).

Except by locking to an earlier version, you can't rely on support/bugfixes, unless you ask for them specifically. (You can track the release notes - they're usually very, very short and to the point).

Summary: if you lock to `~> 3.0.x`, you should be able to install Listen on an older Ruby. But that doesn't mean there's any ongoing "support". Given you can do this, adding support form Ruby 2.1 in Listen > 3.0 doesn't make sense.

IMHO it's much more productive to focus on the making the next Debian become the new "stable", rather than bending over backwards to support the old stable Debian.

Let me know if that helps.

If you have any specific problem, just open a new issue.

**Comment by e2** [comment]
I'm closing this, since there are workarounds on both the Debian side (building and linking a newer Ruby, although that's work) and locking to an earlier version of Listen (which shouldn't be a problem).

Even if I added "support", it wouldn't tested (not by me at least), so it would be a lie to suggest Ruby 2.1 is supported by Listen.

Debian can make strong claims about stability - and I'm making a strong claim here that even if Listen 3.x could be installed on Ruby 2.1, it wouldn't be "supported" by me (bugfixes).

Travis builds of Listen are already horrible right now, anyway.

**Comment by e2** [comment]
FWIW, the "problem" comes from the fact that Debian 8.0 was released almost 2 months after "stable" Ruby 2.2.1 was released:

https://www.ruby-lang.org/en/news/2015/03/03/ruby-2-2-1-released/

This was a mistake on the Debian side IMHO. Oh well...

**Comment by njt1982** [comment]
For reference/anyone else that stumbles upon this problem:

```
group :test do
  gem 'spork'
  gem 'guard-spork'

  # Maintain compatibility with Ruby <2.2 - remove these when we upgrade
  gem 'listen', '~> 3.0.0'
end
```

I needed to do exactly this (not `~> 3.0.x` as mentioned above, for some reason, that still tried to use the 3.1.x branch).

**Comment by e2** [comment]
@njt1982 - aah, yes. By "x" I mean" whatever version is latest.

I mean '~> 3.0.8' , but I was too lazy to look up the last released version. Sorry for that.

('~> 3.0.x' is pretty much the same as '~> 3.0.beta' or something, so RubyGems skips that).
