### ISSUE TITLE
Too many orphaned processes on OSX in Rails

### ISSUE THREAD

**Issue by penne12** [guard/listen#412]
See [issue on the rails repo](https://github.com/rails/rails/issues/26158).

**Comment by e2** [comment]
This should be reported on https://github.com/thibaudgg/rb-fsevent

That's because Rails Spring listener creates the forks and rb-fsevent creates the processes.

Listen can't really do much here to fix this (as far as I know), unless the watchers aren't being closed properly.

There's also a quite recent commit like this: https://github.com/thibaudgg/rb-fsevent/commit/c9deae077d0ecbecf75e7e4106ffd9dd87f5b2f5

So you may want to try different rb-fsevent versions (including earlier ones) - or even build a gem from the rb-fsevent master branch.

Also, Listen (or rb-fsevent) may be crashing - and not closing the processes for some reason.

You may want to try running Listen in debug mode with an environment variable like: `export LISTEN_GEM_DEBUGGING=1` or `export LISTEN_GEM_DEBUGGING=2`.

You might want to check if the above code in rb-fsevent (for killing the process and closing the pipe) if it actually works.

**Comment by penne12** [comment]
@e2 don't really want to test it out, as I found a workaround, and I don't want to have to reboot.
