### ISSUE TITLE
Question: Long polling?

### ISSUE THREAD

**Issue by flyinbutrs** [guard/listen#423]
Hi,

The app I'm writing could benefit from Listen, but it would be used on a long polling window.

Is there any performance or output impact to having an extremely long polling time, like an hour or day? 
If a file is created or modified and then deleted, does it get an entry in both arrays?
If a file is edited multiple times in the polling window, does it get multiple entries?

Thanks,

-Dan

**Comment by rye** [comment]
@flyinbutrs, I am by no means an expert on this project. With that caveat out of the way,

Polling, with Listen, is more CPU- and IO-intensive. When I've used `listen` in environments where polling is the only option, I've noticed significantly increased IO operations when polling takes place.  This is because it's checking every file in the file system, as you might expect.

From my examination of the polling adapter, it appears that having an "extremely long poll time" e.g. an hour or a day will work fine, though, and if a sudden flood of events is okay, then it's perfectly suitable.

You can think of "polls" (each time Listen polls for changes) as snapshots in time, and Listen has no clue what happens outside of these snapshots because it's just comparing between them. For instance, this means that if a file is created and then deleted _between_ polls, to Listen it will be as if that file never existed. Likewise, if a file is is modified multiple times, only the overall change will be noticed.

Please let me know if you have any further questions or clarifications that I can provide.
